version: "3.9"
services:

  main:
    container_name: qbittorrentNox-dev
    build:
      context: src
    ports:
      - 3649:3649
      - 33333:33333
    volumes:
      - ./temp/volume/qBittorrent:/app/qBittorrent
      - ./temp/volume/content:/app/content
      - ./temp/volume/media:/app/media
