version: "3.9"
services:

  main:
    container_name: qbittorrentNox-dev
    network_mode: container:gluetun
    build:
      context: src
    volumes:
      - ./temp/volume/qBittorrent:/app/qBittorrent
      - ./temp/volume/content:/app/content
      - ./temp/volume/media:/app/media
