version: "3.9"
services:
  app:
    container_name: qbittorrent-nox
    restart: no
    image: jaidchen/qbittorrent-nox:latest
    ports:
      - 3649:3649
      - 33333:33333
    volumes:
      - ./config:/home/app/qBittorrent
      - ./finished:/home/app/content/finished
      - ./downloading:/home/app/content/downloading
      - ./torrentBackup:/home/app/content/torrentBackup
      - ./inbox:/home/app/content/inbox
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"
