version: "3.9"
services:
  app:
    container_name: qbittorrent-nox
    restart: unless-stopped
    image: jaidchen/qbittorrent-nox
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - ./dockerVolume/config:/home/app/qBittorrent
      - ./dockerVolume/finished:/home/app/content/finished
      - ./dockerVolume/downloading:/home/app/content/downloading
      - ./dockerVolume/torrentBackup:/home/app/content/torrentBackup
      - ./dockerVolume/inbox:/home/app/content/inbox
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      - 3649:3649/tcp # qbittorrent-nox web ui
      # - $directPort:$directPort # qbittorrent-nox
    environment:
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
    env_file: ./.env
    volumes:
      - ./dockerVolume/gluetun:/gluetun
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"
